// AWS Amplify Configuration Provider for CampusRoom
// Reads directly from amplify_outputs.json generated by Amplify Gen 2
import outputs from "../amplify_outputs.json";

export const awsConfig = {
  aws_project_region: outputs.auth?.aws_region || "ap-south-1",
  aws_cognito_identity_pool_id: outputs.auth?.identity_pool_id || "",
  aws_cognito_region: outputs.auth?.aws_region || "ap-south-1",
  aws_user_pools_id: outputs.auth?.user_pool_id || "",
  aws_user_pools_web_client_id: outputs.auth?.user_pool_client_id || "",
  aws_appsync_graphqlEndpoint: outputs.data?.url || "",
  aws_appsync_region: outputs.data?.aws_region || "ap-south-1",
  aws_appsync_authenticationType: outputs.data?.default_authorization_type || "AMAZON_COGNITO_USER_POOLS",
  aws_user_files_s3_bucket: outputs.storage?.bucket_name || "",
  aws_user_files_s3_bucket_region: outputs.storage?.aws_region || "ap-south-1",
  isConfiguredWithLiveAws: Boolean(
    outputs.auth?.user_pool_id &&
    outputs.data?.url
  ),
  outputs,
};

export default awsConfig;
