// High-fidelity Initial Seed Data for CampusRoom — Matching Stitch Project Designs

export const initialUsers = [
  {
    id: "usr-faculty-01",
    name: "Dr. Sarah Chen",
    email: "sarah.chen@university.edu",
    role: "STAFF",
    roleLabel: "Faculty Researcher",
    department: "Computer Science & AI",
    studentOrStaffId: "FAC-88421",
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDcWR-fkRv-h1CNbotkRRWFNn_co3Jt2dTdHeLkiZScvrE47XXKoBexskdVhmupKj3hCCwl6EkmmsS6xHXsNopXP4E3yk4UTAC2hBlHd0fFU1R313_tw7dcpW-qKUPkLMp2HNE9VccxdI2ORknjryaDlpWNfwgkYp6YPddOL92jRltcklCsS20eqPLdNdVgP67mbDC7_u0V-HPDXU_j5aj5Yk1yA9Xo5zkeUeHMpPwSWR1mxqemSWXB8w",
  },
  {
    id: "usr-student-01",
    name: "Alex Rivera",
    email: "alex.rivera@university.edu",
    role: "STUDENT",
    roleLabel: "Senior Undergrad Student",
    department: "Software Engineering",
    studentOrStaffId: "STU-10943",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
  },
  {
    id: "usr-admin-01",
    name: "Marcus Bradley",
    email: "marcus.bradley@university.edu",
    role: "ADMIN",
    roleLabel: "Campus Facilities Director",
    department: "Academic Infrastructure & Operations",
    studentOrStaffId: "ADM-00412",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80",
  },
];

export const initialRooms = [
  {
    id: "room-tr-301",
    code: "CMP-301",
    name: "Turing Innovation Hub 301",
    building: "Turing Computing Complex",
    campusSector: "North Campus",
    floor: "Floor 3 • West Wing",
    capacity: 24,
    roomType: "LAB",
    typeLabel: "Computing Lab",
    facilities: ["86\" 4K Touchscreen", "Zoom Conference Bar", "High-Speed Wi-Fi 6E", "Ergonomic Wheeled Desks", "Whiteboard", "Dual Displays"],
    status: "AVAILABLE",
    custodian: "Marcus Bradley",
    instantBookable: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDbFLd9JtcqW1YZfPnBHEzSZ1GcZwCEnQi-2M-68jRfvARXc8381xpLopW6Nb8xpWtVuh4BsC0IkuD4a081M1bKZ0zozSVABYi6maESQL5GGZNqqbjAVXDxtJjdEW0JnuPHyImXSxwBdm8GPxWiB4IiKKicA1QKDcXzaklNH0Jp7G-1M9yZrutAzmefkjlmwdbkY_IEZiSrpgdDoD1q8Slcsl97e7T_CXt-UOUAaeY7tD-hKoH7VOHNtA",
    description: "State-of-the-art interactive computer science collaboration lab equipped with high-speed development workstations and video-conferencing bars.",
  },
  {
    id: "room-tr-204",
    code: "TR-204",
    name: "Turing Collab Lab 204",
    building: "Turing Computing Complex",
    campusSector: "North Campus",
    floor: "Floor 2 • West Wing",
    capacity: 12,
    roomType: "LAB",
    typeLabel: "Team Lab",
    facilities: ["4K Display", "Dual Whiteboard", "Video Conference", "Power Outlets", "Wi-Fi 6E"],
    status: "AVAILABLE",
    custodian: "Marcus Bradley",
    instantBookable: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD6ahGQPAj09670JkNG57qe2DQSe4cmE5VLXRNkX5ZtP1l0D4Ro3wSsp9auhLQGMEk06UsBjnzyy88CIUEfhMRY2b9Jfjru6k_0bq8M0wFjYpN72jkVL1y-KR1zyJI0PH3S51OrKL6yEUt5nk8ZKnUzWCSRJTs1nLQlMSofewH6mD9f718fCHrAQ_n0zos2nAoGV89JAf_4nUOerRufEZt9dqCeUeY8nOWS9ONIpU_rIvj7ijNh8gL2lQ",
    description: "Modern university collaboration lab with dual glass whiteboards, 4K digital screen, ergonomic task chairs, and natural lighting.",
  },
  {
    id: "room-sc-aud-a",
    code: "SC-AUD-A",
    name: "Science Hall Auditorium A",
    building: "Science & Engineering Hall",
    campusSector: "North Campus",
    floor: "Floor 1 • Main Atrium",
    capacity: 180,
    roomType: "AUDITORIUM",
    typeLabel: "Auditorium",
    facilities: ["Laser Projector", "Wireless Mic System", "Lecture Capture", "ADA Accessible Tier 1", "Air Conditioning"],
    status: "AVAILABLE",
    custodian: "Eleanor Vance",
    instantBookable: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4DvO8n3ROqSzvyibreybknO4NYEOrRTRa2BmX0NzyKeygQD5sK1a4Ri12A-RHHVx5s4rZY0xOAKEvjYkBwALmHrDosXAkmOQUNU3kCUg0jATT3ddKL77xcxccjWg4UIuSHCJ0SGI-FfIj8gnABQjY81wnENdLty-_24d4k97GwXoay-Pi0EPdMpICYHT55iD0gjwtGzmOkMVPBsfFw8uDrhLcxVHEZua-K6T4d0_JrfIdD0HFPxgj1g",
    description: "Grand tiered lecture auditorium featuring dual laser projection screens, sapphire upholstered acoustic seating, and natural daylight rays.",
  },
  {
    id: "room-sc-lov-b",
    code: "SC-LOV-B",
    name: "Lovelace Seminar Hall B",
    building: "Science & Engineering Hall",
    campusSector: "North Campus",
    floor: "Floor 1 • East Wing",
    capacity: 35,
    roomType: "SEMINAR",
    typeLabel: "Seminar Hall",
    facilities: ["AV Podium", "Lecture Capture", "Wireless Mic", "Projector", "Wi-Fi 6E"],
    status: "AVAILABLE",
    custodian: "Eleanor Vance",
    instantBookable: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBlxL6ajTUSBSwrayILpOy2fbl_5HvMTw-RXR9DYu-0uGtk-dF4WiONp46sms-UkNHp1wnnxr8DasUUoc0IFPtusCwxvJ7TAIpgp_p6TdE64250MRbkBmWahLT0U4CV6sAvAzmky4KKdxb9fj8afg8DxZvWimigHlbxeEwl0y9cVnJBVr0u4kZcMogsk-RMVjyZqgQ0kuAgk60Vuvd-h7BYkFCZoQUWQbaYOs4rkQT6_3HW-cRfqATPiQ",
    description: "University academic seminar hall with tiered seating, digital speaker podium, and dual overhead lecture capture projectors.",
  },
  {
    id: "room-lib-pod-12",
    code: "LIB-POD-12",
    name: "Curie Quiet Pod 12",
    building: "Central Library",
    campusSector: "South Campus",
    floor: "Floor 3 • Silent Zone",
    capacity: 4,
    roomType: "STUDY_POD",
    typeLabel: "Quiet Study Pod",
    facilities: ["Acoustic Glass", "Dual USB-C PD", "Ultra-wide Display", "Power Outlets", "Wi-Fi 6E"],
    status: "AVAILABLE",
    custodian: "Library Staff",
    instantBookable: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCzmTam_qiu-tpbx90mteBwVTIRhoINuzDUkdY96dgczPtNoQRmBzrTi-g7bfz92-cCCmCEhOPvcFYXkpFam8sZLq5vhmn-KmOJZMK4UzW1qpxrMrqS9kM7ShOAPIQ9tPKU68M0XEXIWa1Go-pMroiFxU0qAmfrwEat9B6EiF1L0qfAAdVnNhW6xH3sHX0YVO6HjYbXTkEPmiRHwTTEkZGZvpBARYJsW_Xaucgses6n2N6ekXA7SbHjag",
    description: "Soundproof acoustic private study pod in contemporary campus library with wooden acoustic wall slats and ultra-wide monitor.",
  },
  {
    id: "room-env-108",
    code: "ENV-108",
    name: "Goodall Seminar 108",
    building: "Environmental Sciences",
    campusSector: "South Campus",
    floor: "Floor 1 • East Wing",
    capacity: 16,
    roomType: "SEMINAR",
    typeLabel: "Seminar Room",
    facilities: ["Dual Whiteboard", "Power Outlets", "Video Conference", "Wi-Fi 6E"],
    status: "MAINTENANCE",
    custodian: "David Thorne",
    instantBookable: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCUNh_PueOpt-KqofRRgQOXE7VqZAqqmiivGgHA1K6WqK155AtcORC8E4mgN6ggGtjJWEloWUM-u8RBt6zuODosK1lxDrc_SgKbnTWpf-Vq_-p5MA_9NCRC_fBOq9MSHuGQJzVSzAArT70NWNUwv04EcXV2sK2n7IIrbESpcrJBnWhAF4ak4kqN4T7g7GhgUNem-0RRyZsTV8JApph1F3Ds1yX9NGuX-pHdzp4ER0MX64T2DAsDrLOd6A",
    description: "Quiet contemporary seminar room with wooden conference table and ergonomic chairs. Currently under projector maintenance.",
  },
  {
    id: "room-bak-105",
    code: "BAK-105",
    name: "Baker Study Suite 105",
    building: "Baker Humanities Center",
    campusSector: "South Campus",
    floor: "Floor 1 • South Corridor",
    capacity: 8,
    roomType: "CONFERENCE",
    typeLabel: "Study Suite",
    facilities: ["Projector", "Whiteboard", "Power Outlets", "Air Conditioning"],
    status: "AVAILABLE",
    custodian: "David Thorne",
    instantBookable: true,
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    description: "Cozy humanities conference space with collaborative table, presentation screen, and whiteboards.",
  },
  {
    id: "room-bio-aud",
    code: "BIO-AUD-A",
    name: "BioTech Auditorium A",
    building: "BioTech Research Center",
    campusSector: "North Campus",
    floor: "Floor 1 • Main Concourse",
    capacity: 120,
    roomType: "AUDITORIUM",
    typeLabel: "Auditorium",
    facilities: ["Dual Laser Projector", "Wireless Mic", "Lecture Capture", "ADA Accessible Tier 1"],
    status: "AVAILABLE",
    custodian: "Marcus Bradley",
    instantBookable: false,
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80",
    description: "Large biosciences presentation auditorium equipped with dual laser projection and professional sound reinforcement.",
  },
  {
    id: "room-hop-410",
    code: "HOP-410",
    name: "Hopper GPU Compute Lab 410",
    building: "Turing Computing Complex",
    campusSector: "North Campus",
    floor: "Floor 4 • High Performance Lab",
    capacity: 30,
    roomType: "LAB",
    typeLabel: "Research Lab",
    facilities: ["Dual 4K Displays", "GPU Clusters", "Gigabit LAN", "Video Conference", "Wi-Fi 6E"],
    status: "AVAILABLE",
    custodian: "Marcus Bradley",
    instantBookable: true,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCZvK55_agKC5MBZolenIum1tnaMg1yrpnr6ZqevQvNMy5b7YuySq4Id9xP_sNkdG6Tb9lssKh_1uVszMFwIQB6ywhaMcgmNGuE67IDmeJlgm5piEwYuz_0YHkb3i00BVpjMsim7_5WV--9qb-cTj5ZF0YL7s4ROwv7YJ3usb0L2OKv0NCLiT9wjVLsqSYVA5QsCU7-gQ46MaZGManT1fsV2nYJizk-TbpkuGexskAQOr_jlbIxniSZYQ",
    description: "Advanced machine learning and parallel computing laboratory featuring workstation nodes and dual high-resolution monitors.",
  },
];

// Helper to get formatted date relative to today
const getRelativeDate = (offsetDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split("T")[0];
};

export const initialBookings = [
  {
    id: "bk-1001",
    userId: "usr-faculty-01",
    userName: "Dr. Sarah Chen",
    userRole: "STAFF",
    roomId: "room-tr-204",
    roomName: "Turing Lab 204",
    roomCode: "TR-204",
    building: "Turing Computing Complex",
    date: getRelativeDate(0), // Today
    startTime: "14:00",
    endTime: "15:30",
    purpose: "AI Project Sprint",
    attendeeCount: 8,
    status: "CONFIRMED",
    syncState: "SYNCED",
    keycardPin: "8392",
    qrPassCode: "PASS-TR204-8392",
    createdAt: new Date().toISOString(),
  },
  {
    id: "bk-1002",
    userId: "usr-faculty-01",
    userName: "Dr. Sarah Chen",
    userRole: "STAFF",
    roomId: "room-bio-aud",
    roomName: "BioTech Auditorium A",
    roomCode: "BIO-AUD-A",
    building: "BioTech Research Center",
    date: getRelativeDate(1), // Tomorrow
    startTime: "10:00",
    endTime: "12:00",
    purpose: "Faculty Research Board",
    attendeeCount: 45,
    status: "CONFIRMED",
    syncState: "SYNCED",
    keycardPin: "4419",
    qrPassCode: "PASS-BIOAUD-4419",
    createdAt: new Date().toISOString(),
  },
  {
    id: "bk-1003",
    userId: "usr-faculty-01",
    userName: "Dr. Sarah Chen",
    userRole: "STAFF",
    roomId: "room-bak-105",
    roomName: "Baker Study Suite 105",
    roomCode: "BAK-105",
    building: "Baker Humanities Center",
    date: getRelativeDate(2),
    startTime: "16:00",
    endTime: "17:30",
    purpose: "Student Office Hours",
    attendeeCount: 4,
    status: "PENDING",
    syncState: "PENDING_LOCAL",
    keycardPin: "6120",
    qrPassCode: "PASS-BAK105-6120",
    createdAt: new Date().toISOString(),
  },
  {
    id: "bk-1004",
    userId: "usr-student-01",
    userName: "Alex Rivera",
    userRole: "STUDENT",
    roomId: "room-lib-pod-12",
    roomName: "Curie Quiet Pod 12",
    roomCode: "LIB-POD-12",
    building: "Central Library",
    date: getRelativeDate(0), // Today
    startTime: "18:00",
    endTime: "20:00",
    purpose: "Capstone Research Focus",
    attendeeCount: 2,
    status: "CONFIRMED",
    syncState: "SYNCED",
    keycardPin: "2941",
    qrPassCode: "PASS-LIB12-2941",
    createdAt: new Date().toISOString(),
  },
  {
    id: "bk-1005",
    userId: "usr-student-01",
    userName: "Alex Rivera",
    userRole: "STUDENT",
    roomId: "room-sc-aud-a",
    roomName: "Science Hall Auditorium A",
    roomCode: "SC-AUD-A",
    building: "Science & Engineering Hall",
    date: getRelativeDate(3),
    startTime: "14:00",
    endTime: "17:00",
    purpose: "Annual ACM Hackathon Keynote",
    attendeeCount: 150,
    status: "PENDING",
    syncState: "SYNCED",
    keycardPin: null,
    qrPassCode: null,
    adminNotes: "Awaiting Facilities Department AV verification",
    createdAt: new Date().toISOString(),
  },
];

export const initialNotifications = [
  {
    id: "notif-01",
    userId: "usr-faculty-01",
    title: "Reservation Confirmed",
    message: "Your booking for Turing Lab 204 today at 2:00 PM is confirmed. Keycard access PIN: 8392.",
    type: "BOOKING_CONFIRMED",
    isRead: false,
    timestamp: "10 minutes ago",
  },
  {
    id: "notif-02",
    userId: "usr-faculty-01",
    title: "Amplify DataStore Synced",
    message: "128 campus spaces refreshed from AWS DynamoDB. Low latency offline conflict verification active.",
    type: "SYSTEM",
    isRead: false,
    timestamp: "1 hour ago",
  },
  {
    id: "notif-03",
    userId: "usr-faculty-01",
    title: "Maintenance Notice",
    message: "Goodall Seminar 108 is currently undergoing AV projector maintenance until tomorrow morning.",
    type: "MAINTENANCE_ALERT",
    isRead: true,
    timestamp: "3 hours ago",
  },
  {
    id: "notif-04",
    userId: "usr-student-01",
    title: "Quiet Pod Reserved",
    message: "Curie Quiet Pod 12 reserved for today 6:00 PM – 8:00 PM. Access PIN: 2941.",
    type: "BOOKING_CONFIRMED",
    isRead: false,
    timestamp: "30 minutes ago",
  },
];
